# Generated by Django 5.0.6 on 2024-05-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Whatsapp'),
        ),
    ]
