# Generated by Django 5.0.6 on 2024-05-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usermodel_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='customer_stripe_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='lang_for_communication',
            field=models.CharField(default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='subscription_canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='subscription_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='subscription_status',
            field=models.IntegerField(choices=[(1, 'trial'), (2, 'trial_ended'), (3, 'subscription_paid'), (4, 'subscription_unpaid'), (5, 'subscription_cancelled')], default=1),
        ),
    ]
