# Generated by Django 5.0.6 on 2024-05-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usermodel_customer_stripe_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='subscription_failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
