# Generated by Django 5.0.6 on 2024-05-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_usermodel_subscription_failed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='fcmToken',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='subscription_status',
            field=models.IntegerField(choices=[(1, 'trial'), (2, 'trial_ended'), (3, 'subscription_paid'), (4, 'subscription_unpaid'), (5, 'subscription_canceled')], default=1),
        ),
    ]
