# Generated by Django 5.0.6 on 2024-06-05 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_usermodel_fcmtoken_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='lang_for_communication',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='customer_country',
            field=models.CharField(default='BR', max_length=2),
            preserve_default=False,
        ),
    ]
