# Generated by Django 4.2.10 on 2024-04-19 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.journalgroup'),
        ),
        migrations.AlterField(
            model_name='note',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.notegroup'),
        ),
        migrations.AlterField(
            model_name='term',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.termgroup'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.todogroup'),
        ),
    ]
