# Generated by Django 4.2.9 on 2024-02-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_todo_created_at_alter_todo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='term',
            name='term',
            field=models.CharField(max_length=255, verbose_name='Term'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
