# Generated by Django 4.2.10 on 2024-04-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_journal_group_alter_note_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='term',
            name='definition',
            field=models.CharField(max_length=500, verbose_name='Definition'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Description'),
        ),
    ]
