# Generated by Django 4.2.10 on 2024-04-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_note_text_alter_term_definition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.IntegerField(choices=[(1, 'Postponed'), (2, 'Pendent'), (3, 'Doing'), (4, 'Done')], default=2),
        ),
    ]
