# Generated by Django 4.2.10 on 2024-04-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_todo_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=70, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='term',
            name='term',
            field=models.CharField(max_length=70, verbose_name='Term'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=70, verbose_name='Title'),
        ),
    ]
