# Generated by Django 4.2.10 on 2024-04-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_note_title_alter_term_term_alter_todo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='notegroup',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
