# Generated by Django 4.2.10 on 2024-04-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_notegroup_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalgroup',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='termgroup',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todogroup',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
