# Generated by Django 4.2.10 on 2024-04-26 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_journalgroup_order_termgroup_order_todogroup_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_records', to='core.journalgroup'),
        ),
    ]
