# Generated by Django 4.2.10 on 2024-04-26 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_journal_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_records', to='core.notegroup'),
        ),
        migrations.AlterField(
            model_name='term',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_records', to='core.termgroup'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_records', to='core.todogroup'),
        ),
    ]
