# Generated by Django 4.2.10 on 2024-04-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_note_group_alter_term_group_alter_todo_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.CharField(max_length=551, verbose_name='Text'),
        ),
    ]
