# Generated by Django 4.2.10 on 2024-04-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_note_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=117, verbose_name='Title'),
        ),
    ]
