# Generated by Django 4.2.10 on 2024-04-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='definition',
            field=models.CharField(max_length=551, verbose_name='Definition'),
        ),
        migrations.AlterField(
            model_name='term',
            name='term',
            field=models.CharField(max_length=135, verbose_name='Term'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.CharField(max_length=551, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=135, verbose_name='Title'),
        ),
    ]
