# Generated by Django 4.2.10 on 2024-04-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_term_definition_alter_term_term_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='done_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Done date'),
        ),
    ]
