# Generated by Django 5.0.6 on 2024-05-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_todo_done_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.TextField(verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='term',
            name='definition',
            field=models.TextField(verbose_name='Definition'),
        ),
        migrations.AlterField(
            model_name='term',
            name='term',
            field=models.TextField(verbose_name='Term'),
        ),
    ]
