# Generated by Django 5.0.6 on 2024-05-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_journal_text_alter_note_text_alter_note_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Urgent'), (2, 'High'), (3, 'Normal'), (4, 'Low')], default=3),
        ),
    ]
