# Generated by Django 5.0.6 on 2024-05-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_note_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='todogroup',
            name='filter_priority',
            field=models.IntegerField(blank=True, choices=[(1, 'Urgent'), (2, 'High'), (3, 'Normal'), (4, 'Low')], null=True),
        ),
        migrations.AddField(
            model_name='todogroup',
            name='filter_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Postponed'), (2, 'Pendent'), (3, 'Doing'), (4, 'Done')], null=True),
        ),
    ]
