# Generated by Django 5.0.6 on 2024-05-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_todogroup_filter_priority_todogroup_filter_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.TextField(verbose_name='Title'),
        ),
    ]
