# Generated by Django 5.0.6 on 2024-05-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_todo_description_alter_todo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='term',
            name='definition',
            field=models.TextField(blank=True, null=True, verbose_name='Definition'),
        ),
        migrations.AlterField(
            model_name='term',
            name='term',
            field=models.TextField(blank=True, null=True, verbose_name='Term'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Title'),
        ),
    ]
