# Generated by Django 5.0.6 on 2024-05-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_journal_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='notify_on_due',
            field=models.BooleanField(default=False),
        ),
    ]
